### ISSUE TITLE
No error in Response (in async) when checking with a bad checksum

### ISSUE THREAD

**Issue by Skywalker13** [cavaliercoder/grab#11]
Hello,

When using `client.DoAsync` and the checksum functionality, if the checksum is different, this error is not available in `resp.Error` (this value is nil). I must check if the file exists in order to detect this sort of error because I've set `RemoveOnError` on the request.

Regards

**Comment by Skywalker13** [comment]
Forget it.. my bad

**Comment by cavaliercoder** [comment]
Thanks for updating. In case anyone else stumbles on this, where was the confusion?

**Comment by Skywalker13** [comment]
I was not testing the right error object... it was just a stupid mistake

But there is at least one point where it's a bit confusing according to http://cavaliercoder.com/blog/downloading-large-files-in-go.html
- When using a checksum, the expected file size **must be set too**, otherwise the checksum is ignored
