### ISSUE TITLE
Optionally allow GET+Range 0-0 instead of HEAD

### ISSUE THREAD

**Issue by ryanjyoder** [cavaliercoder/grab#16]
AWS S3 buckets are capable of generating temporary signed url, which grant access to an object for a limited amount of time. Unfortunately grab is not able to download these urls, because the url must be signed with the http verb. In other words the same url cannot be used for both a GET and HEAD request.

It would be helpful for us to simulate a HEAD request with GET + `Range: bytes=0-0`. If this was an option on the request, users could use the default or override it with a GET request if needed.

Willing to submit a PR if you'd like to support this option.

**Comment by cavaliercoder** [comment]
Interesting problem! If you set `request.NoResume = true`, grab will skip the HEAD request and proceed directly to the GET request. I understand this breaks the ability to resume signed downloads from S3.

I'm happy to explore the solution you have proposed (PR welcome), but I worry that the `GET + Range` solution might have unexpected behaviours on a more diverse range of web servers. Potentially, a request flag could be added to attempt resuming without first checking for support. If the response isn't a partial, grab could return an error.

**Comment by cavaliercoder** [comment]
Further compounding this issue, `bytes=0-0` will cause the remote server to report `Content-Length: 0` - reducing the value of the first `HEAD` request.

My advice is to skip the initial `HEAD` request by setting `request.NoResume = true`. Resuming incomplete downloads doesn't seem practical given the constraints of signed URLs.
