### ISSUE TITLE
Get the resp.Size first, then download it

### ISSUE THREAD

**Issue by fslove** [cavaliercoder/grab#39]
Have a file locally, size: 800kb
Download if the remote file size is larger than 800kb

**Comment by cavaliercoder** [comment]
Hi, I'd love to help with your issue, but it isn't clear to me what you need. Can you please elaborate the problem you are trying to solve?

Grab will already download the remote file if it is larger than the local file. It will overwrite it if `NoResume==true`.

**Comment by senioi** [comment]
thanks for your help.
