### ISSUE TITLE
Cannot download html file

### ISSUE THREAD

**Issue by kamontat** [cavaliercoder/grab#41]
When I try to download `https:/google.com` html file. 

1. Resp.Size return `1.4 GiB`

**Comment by kamontat** [comment]
Cause error: `bad content length`

**Comment by cavaliercoder** [comment]
Thanks for raising this issue. Can you please help me to reproduce this problem? I don't see the same issue.

**Comment by kamontat** [comment]
When I try to download html file, error `bad content length` was threw.

**Comment by kamontat** [comment]
But the result are fine,

**Comment by cavaliercoder** [comment]
If you still have this issue, please reopen and provide code samples and URLs so that I can reproduce the issue.
