### ISSUE TITLE
making getbatch accepts multiple destinations 

### ISSUE THREAD

**Issue by hbakhtiyor** [cavaliercoder/grab#49]
currently getbatch accept only one destination, can't set filename for each urls.

**Comment by cavaliercoder** [comment]
GetBatch is a very simple abstraction that doesn't allow granular configuration of each request, like distinct destination paths. Under the hood, it creates Requests for you and passes them to `Client.DoBatch`.

To configure each request, create as many unique sRequests as you like and pass them directly to `Client.DoBatch`. See: https://godoc.org/github.com/cavaliercoder/grab#Client.DoBatch
