### ISSUE TITLE
Download Speed

### ISSUE THREAD

**Issue by ohenepee** [cavaliercoder/grab#6]
How can I get the download speed?

**Comment by ohenepee** [comment]
Found this ONLINE... maybe you could integrate it

**Comment by cavaliercoder** [comment]
`Response.AverageBytesPerSecond()` will give you the average speed over the duration of the transfer and is constantly updated while the transfer is in process. It works precisely how you described.

I'm looking to implement a `CurrentBytesPerSecond` function, but this will require an additional timer to mark the passage of each second. It's also frightfully difficult to produce nice steady and accurate numbers when updating on a timer.
