### ISSUE TITLE
Grab can't determine filename with an URL where this looks pretty easy

### ISSUE THREAD

**Issue by onodera-punpun** [cavaliercoder/grab#64]
URL in question: https://dl.google.com/go/go1.11beta1.src.tar.gz

Fails with both `cmd/grab` and using grab as a library, wget can correctly determine the filename.

grab output:

```
./grab https://dl.google.com/go/go1.13beta1.src.tar.gz
Downloading 1 files...
Error downloading https://dl.google.com/go/go1.13beta1.src.tar.gz: no filename could be determined
Finished 0 successful, 1 failed, 0 incomplete.
```

**Comment by riyaz-ali** [comment]
@onodera-punpun This is because `dl.google.com` is returning `Content-Disposition` header without any `filename` directive!

<img width="877" alt="Screenshot 2019-10-26 at 10 44 14 PM" src="https://user-images.githubusercontent.com/17478576/67623392-4f17ca80-f842-11e9-9e82-2034edefaab4.png">
