### ISSUE TITLE
 return grab.GetAsync implementation

### ISSUE THREAD

**Issue by gromo3eka** [cavaliercoder/grab#65]
could you please return grab.GetAsync implementation? it lost somewhere in previous commits. or please advice an alternative for this function.

**Comment by igroykt** [comment]
hi. agree.

> undefined: grab.GetAsync

**Comment by cavaliercoder** [comment]
Here is the old version: https://github.com/cavaliercoder/grab/blob/b1b0e34b676d760bffa187e04d97302e9cce2a94/grab.go#L64
