### ISSUE TITLE
download file from go-fastdfs

### ISSUE THREAD

**Issue by fcddk** [cavaliercoder/grab#66]
no filename could be determined
2019/09/29 16:44:31 E! DownloadFile client connect error: no filename could be determined

code:	

func main()  {
	err := downloadFile("http://10.110.18.101:30039/group1/agent/ecs-monitor-03-linux64-amd64.tar.gz")
	if err != nil {
		fmt.Println(err)
	}
}

func downloadFile(httpUrl string) error {
	//client := grab.NewClient()

	_, err := grab.Get(".", httpUrl)
	if err != nil {
		log.Printf("E! DownloadFile new Request error: %s", err.Error())
		return err
	}

	//resp := client.Do(req)
	//if err = resp.Err(); err != nil {
	//	log.Printf("E! DownloadFile client connect error: %s", err.Error())
	//	return err
	//}
	//defer resp.Cancel()

	return nil
}

**Comment by riyaz-ali** [comment]
This is related to #64 and should be fixed by #67 .. I propose to close this issue..
